name: Group 43 CI CD Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true
      - uses: iterative/setup-cml@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Packages
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Lint Code
        run: flake8 .
      - name: Format Code
        run: black *.py
      - name: Train
        run: python age_model.py
      - name: Run Tests
        run: pytest age_model_test.py
      - name: Deploy Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          python age_model.py
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
            
          echo '## Confusion Matrix Plot' >> report.md
          echo '![Confusion Matrix](age_pred_model_results.png)' >> report.md

          cml comment create report.md
